export enum BrowserFeatureKey {
    ServiceWorker = 'Service Worker',
    Cache = 'Offline Capabilities',
    PushAPI = 'Push data',
    NotificationsAPI = 'Notifications',
    BeforeInstallPromptEvent = 'Add to Homescreen',
    BackgroundSync = 'Background sync',
    NavigationPreloadManager = 'Navigation Preload',
    BudgetAPI = 'Budget API',
    StorageEstimation = 'Storage Estimation',
    PersistentStorage = 'Persistent Storage',
    WebShareAPI = 'Web Share',
    MediaSessionAPI = 'Media Session',
    MediaCapabilities = 'Media Capabilities',
    DeviceMemory = 'Device Memory',
    RelatedApps = 'Getting Installed Related Apps',
    PaymentRequestAPI = 'Payment Request',
    CredentialManagement = 'Credential Management',
    WebBluetoothAPI = 'Web Bluetooth'
}
